---
# vars file for roles/jenkins
jenkins_repo_key: https://pkg.jenkins.io/debian/jenkins.io.key
jenkins_repo: deb https://pkg.jenkins.io/debian-stable binary/
jenkins_package: jenkins
jenkins_service: jenkins
jenkins_port: 8080
